# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-10-29 09:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='data_point',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name_id', models.IntegerField()),
                ('data_name', models.CharField(max_length=64, unique=True)),
                ('show_name', models.CharField(max_length=64, unique=True)),
                ('TLV_Type', models.IntegerField()),
                ('operation_type', models.CharField(max_length=2)),
                ('data_type', models.CharField(max_length=12)),
                ('max_value', models.CharField(blank=True, max_length=64)),
                ('min_value', models.CharField(blank=True, max_length=64)),
                ('step_by_step', models.CharField(blank=True, max_length=64)),
                ('value_unit', models.CharField(max_length=12)),
                ('true_value_name', models.CharField(blank=True, max_length=64)),
                ('true_value_show', models.CharField(blank=True, max_length=64)),
                ('true_bool_value', models.NullBooleanField()),
                ('false_value_name', models.CharField(blank=True, max_length=64)),
                ('false_value_show', models.CharField(blank=True, max_length=64)),
                ('false_bool_value', models.NullBooleanField()),
                ('str_maxlen', models.CharField(blank=True, max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='downstream',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_point', models.ManyToManyField(to='decive.data_point')),
            ],
        ),
        migrations.CreateModel(
            name='ProductModelName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_model', models.CharField(max_length=64, unique=True)),
                ('product_desc', models.CharField(blank=True, max_length=64)),
                ('current_time', models.DateTimeField(auto_now=True)),
                ('create_time', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username')),
            ],
        ),
        migrations.CreateModel(
            name='upstream',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_point', models.ManyToManyField(to='decive.data_point')),
                ('model_name', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='decive.ProductModelName')),
            ],
        ),
        migrations.AddField(
            model_name='downstream',
            name='model_name',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='decive.ProductModelName'),
        ),
    ]
