# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-10-29 09:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('decive', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data_point',
            name='model_name_id',
        ),
    ]
