# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-18 22:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('decive', '0002_remove_deviceinfo_device_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='deviceinfo',
            name='device_user',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username'),
            preserve_default=False,
        ),
    ]
