# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-10-29 09:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('decive', '0002_remove_data_point_model_name_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='data_point',
            name='model_name',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='decive.ProductModelName'),
        ),
    ]
