# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-11-03 09:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decive', '0003_data_point_model_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data_point',
            name='data_name',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='data_point',
            name='show_name',
            field=models.CharField(max_length=64),
        ),
    ]
