# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-11-06 13:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decive', '0004_auto_20181103_0918'),
    ]

    operations = [
        migrations.AddField(
            model_name='downstream',
            name='upstream_Type',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='downstream',
            name='upstream_len',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='downstream',
            name='upstream_name',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AddField(
            model_name='downstream',
            name='upstream_showname',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AddField(
            model_name='upstream',
            name='upstream_Type',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='upstream',
            name='upstream_len',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='upstream',
            name='upstream_name',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AddField(
            model_name='upstream',
            name='upstream_showname',
            field=models.CharField(default='', max_length=64),
        ),
    ]
