# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-11-07 10:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decive', '0005_auto_20181106_1324'),
    ]

    operations = [
        migrations.RenameField(
            model_name='downstream',
            old_name='upstream_Type',
            new_name='downstream_Type',
        ),
        migrations.RenameField(
            model_name='downstream',
            old_name='upstream_len',
            new_name='downstream_len',
        ),
        migrations.RenameField(
            model_name='downstream',
            old_name='upstream_name',
            new_name='downstream_name',
        ),
        migrations.RenameField(
            model_name='downstream',
            old_name='upstream_showname',
            new_name='downstream_point',
        ),
        migrations.AddField(
            model_name='downstream',
            name='downstream_showname',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AddField(
            model_name='upstream',
            name='upstream_point',
            field=models.CharField(default='', max_length=64),
        ),
    ]
