# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-09 23:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('decive', '0006_auto_20181107_1031'),
    ]

    operations = [
        migrations.RenameField(
            model_name='downstream',
            old_name='data_point',
            new_name='up_point',
        ),
        migrations.RenameField(
            model_name='upstream',
            old_name='data_point',
            new_name='up_point',
        ),
    ]
