# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-09 23:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('decive', '0007_auto_20181109_2326'),
    ]

    operations = [
        migrations.RenameField(
            model_name='downstream',
            old_name='up_point',
            new_name='down_point',
        ),
    ]
