# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-12 22:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('decive', '0008_auto_20181109_2327'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deviceinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UUID', models.CharField(blank=True, max_length=12)),
                ('device_name', models.CharField(blank=True, max_length=64)),
                ('device_class', models.CharField(blank=True, max_length=64)),
                ('create_time', models.DateTimeField(auto_now=True)),
                ('model_name', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='decive.ProductModelName')),
            ],
        ),
    ]
