# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-12 23:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decive', '0009_deviceinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deviceinfo',
            name='UUID',
            field=models.CharField(blank=True, max_length=24),
        ),
    ]
