# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-13 21:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('decive', '0011_auto_20181113_2155'),
    ]

    operations = [
        migrations.DeleteModel(
            name='downstream',
        ),
    ]
