# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-13 21:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('decive', '0012_delete_downstream'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upstream',
            name='model_name',
        ),
        migrations.RemoveField(
            model_name='upstream',
            name='up_point',
        ),
        migrations.DeleteModel(
            name='upstream',
        ),
    ]
