# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-13 21:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('decive', '0013_auto_20181113_2158'),
    ]

    operations = [
        migrations.CreateModel(
            name='stream',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stream_showname', models.CharField(default='', max_length=64)),
                ('stream_name', models.CharField(default='', max_length=64)),
                ('stream_point', models.CharField(default='', max_length=64)),
                ('stream_Type', models.IntegerField(null=True)),
                ('stream_len', models.IntegerField(null=True)),
                ('model_name', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='decive.ProductModelName')),
                ('point', models.ManyToManyField(to='decive.data_point')),
            ],
        ),
    ]
