# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-25 18:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decive', '0014_stream'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data_point',
            name='TLV_Type',
            field=models.CharField(default='', max_length=2),
        ),
        migrations.AlterField(
            model_name='stream',
            name='stream_Type',
            field=models.CharField(default='', max_length=2),
        ),
        migrations.AlterField(
            model_name='stream',
            name='stream_len',
            field=models.CharField(default='', max_length=2),
        ),
    ]
