# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-28 21:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decive', '0016_auto_20181125_1812'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UUID', models.CharField(blank=True, max_length=24)),
                ('status', models.CharField(blank=True, max_length=1)),
                ('info', models.CharField(blank=True, max_length=4)),
                ('current_time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
