# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-28 21:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('decive', '0017_devicestatus'),
    ]

    operations = [
        migrations.RenameField(
            model_name='devicestatus',
            old_name='current_time',
            new_name='currenttime',
        ),
    ]
