# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-28 22:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decive', '0018_auto_20181128_2129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicestatus',
            name='info',
            field=models.CharField(blank=True, max_length=8),
        ),
    ]
