# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-11-29 15:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decive', '0019_auto_20181128_2207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicestatus',
            name='info',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
