# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-12-10 10:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('decive', '0020_auto_20181129_1516'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stream',
            name='stream_point',
        ),
    ]
